version: "3.8"
services:
  jenkins:
    container_name: jenkins
    image: aldot25/jenkins:latest
    build:
      context: jenkins_docker
    ports:
      - 8090:8080
    user: "root:jenkins"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.1.0-community
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube_home/data:/opt/sonarqube/data
      - ./sonarqube_home/extensions:/opt/sonarqube/extensions
      - ./sonarqube_home/logs:/opt/sonarqube/logs
      - ./sonarqube_home/temp:/opt/sonarqube/temp
    networks:
      - net
networks:
  net: